### ISSUE TITLE
Multi-features v0.0.5

### ISSUE THREAD

**Issue by perriea** [needpc/front#31]
Multiple feature :
- [x] Disqus (article),
- [x] About us (about),
- [x] Optimization of the number of queries on the PC search (index),
- [x] Replace visualisation (result of PC categorization) .
